from sage.all import Graph

class HourglassPlabicGraph:
    '''Represents an hourglass plabic graph.'''
    def __init__(self):
        self.inner_vertices = []
        self.boundary_vertices = []
        
        self.layout = 'circular'

    # Layout functions
    
    def make_circular(self, radius=10): # TODO: TEST
        n = len(self.boundary_vertices)
        for i,v in self.boundary_vertices:
            v.x = radius*math.sin((i+0.5)*2*math.pi/n)
            v.y = radius*math.cos((i+0.5)*2*math.pi/n)
            
        self.tutte_layout()
        self.layout = "circular"

    def to_graph(self, hourglass_labels=False): # TODO: VERIFY/TEST
        '''Creates an equivalent sagemath Graph. Represents strands in an hourglass in the label.'''
        vertices = inner_vertices + boundary_vertices
        edges = [(h.v_from.id, h.v_to.id, h.label if hourglass_labels else h.strand_count) for h in self.hourglasses.values()]
        pos = {v:(v.x,v.y) for v in vertices}
        g = Graph([vertices,edges],format='vertices_and_edges', pos=pos)
        return g

    def tutte_layout(self, error=0.01, max_iter = 1000):
        '''from https://cs.brown.edu/people/rtamassi/gdhandbook/chapters/force-directed.pdf.'''
        for i in range(max_iter):
            err = 0
            for v in self.inner_vertices():
                neighbours = v.get_neighbors()
                x_new = sum(w.x for w in neighbours)/len(neighbours)
                y_new = sum(w.y for w in neighbours)/len(neighbours)
                err += (v.x-x_new)**2 + (v.y-y_new)**2
                v.x, v.y = x_new, y_new
            if err < error:
                break

    # Trip functions

    def get_trip(self, vertex, i, output='half_strands'):
        ''' vertex: the initial boundary Vertex; assumes multiplicity 1
            i: computes trip_i by taking the ith left at unfilled/ith right at filled
            output: if output = 'half_strands', returns an array of HalfStrands. Otherwise, returns HalfHourglasses.

            Returns the list of HalfHourglasses/HalfStrands the trip visits in order.'''

        assert vertex.is_boundary(), "vertex should be on the boundary."
        assert vertex.total_degree() == 1, "multiplicity of vertex should be 1."
        
        return vertex.get_trip(i, output)

    def get_trip_perm(self, i):
        ''' Computes the ith trip permutation.
            The trip i permutation is generated by finding where trip i sends each boundary vertex to.
            Boundary vertices are assumed to be numbered 1, 2, ..., n CW starting slightly east of due north.'''
        perm = []
        for vertex in self.boundary_vertices:
            trip = vertex.get_trip(i)
            final_vertex = trip[-1].v_to
            perm.append(self.boundary_vertices.index(w)+1)
        return perm

    def get_trip_perms(self):
        '''Returns a list [t_1, ..., t_{r-1}] where t_i is the ith trip permutation
           and r is the maximum degree of an internal vertex.'''
        r = max(v.total_degree() for v in self.inner_vertices)
        return [self.get_trip_perm(i) for i in range(1, r)]